## 실습 1. 튜플형 데이터 (A, B)를 만들고 C를 추가한다.

In [10]:
tp = ('A', 'B', )
lst = list(tp)
lst.append('C')
tp = tuple(lst)
tp

('A', 'B', 'C')

In [ ]:
# 풀이
A = ("A", "B", )
B = ("C", )
C = A + B
C

('A', 'B', 'C')

## 실습 2. 정수 n을 입력받아 n x n 크기의 숫자 사각형을 출력

In [28]:
n = int(input("정수를 입력하시오. "))
result = []  # 결과를 저장할 리스트
temp = 1

for i in range(n):
    row = []  # 각 행을 저장할 리스트
    for j in range(n):
        row.append(temp)  # 현재 숫자를 행에 추가
        temp += 1
    result.append(row)  # 행을 리스트 형태로 결과 리스트에 추가

# 결과 출력
print(result)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
# 풀이
import numpy as np

n = int(input())
A = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        A[i, j] = i*n + j
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


## 실습 3. 실습 2에서 수행한 결과를 reshape을 이용해서 1차원 형태로 변환한다.

In [29]:
import numpy as np

# 결과를 NumPy 배열로 변환하고 1차원 형태로 reshape
result_array = np.array(result)  # 2차원 배열로 변환
reshaped_array = result_array.reshape(-1)  # 1차원 배열로 변환

# 결과 출력
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# 풀이
B = A.reshape(-1, )
print(B)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


## 실습 4

In [21]:
#풀이
import cv2

### transpos
image = cv2.imread('Lenna.png', cv2.COLOR_BGR2RGB)
print(image.shape)
#### expand dims
image_exp = np.expand_dims(image, 0)
print(image_exp.shape)
image_tr = np.transpose(image_exp, [0, 3, 1, 2])
print(image_tr.shape)

(512, 512, 3)
(1, 512, 512, 3)
(1, 3, 512, 512)


## 실습 5

In [ ]:
import cv2
import numpy as np

img = cv2.imread('Lenna.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/intel/.venv/lib/python3.12/site-packages/cv2/qt/plugins"
