In [ ]:
import cv2
import numpy as np

img = cv2.imread('Lenna.png',cv2.IMREAD_GRAYSCALE)
# kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
edge_detect = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])

# print(kernel)
print(edge_detect)

# output = cv2.filter2D(img,-1,kernel)
output = cv2.filter2D(img,-1,edge_detect)

cv2.imshow('filter_test',output)
cv2.waitKey(0)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/inteldx/git-training/DX-01/class01/homework/yangseungyong/ANN_test/.venv/lib/python3.10/site-packages/cv2/qt/plugins"
